package com.duckspot.devops.swing;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JButton;
import javax.swing.JTextArea;

public class LogPanel 
        extends javax.swing.JPanel implements PropertyChangeListener {

    /**
     * Creates new form NewJPanel
     */
    public LogPanel() {
        initComponents();
        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
    }

    private class EnableCloseButton implements Runnable {
        public void run() {
            closeButton.setEnabled(true);
        }
    }
    
    private class PassText implements Runnable {
        String text;
        PassText(String text) {
            this.text = text;
        }
        public void run() {
            logArea.setText(text);
        }        
    }
    
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getSource() instanceof PrintBuilder) {
            switch (evt.getPropertyName()) {
                case "text":
                    String newText = (String)evt.getNewValue();
                    java.awt.EventQueue.invokeLater(new PassText(newText));
                    break;
                case "complete":
                    if ((boolean)evt.getNewValue()) {
                        java.awt.EventQueue.invokeLater(new EnableCloseButton());
                    }
                    break;                
            }
        }
    }
    
    /**
     * get logArea - support for testing
     * @return logArea
     */
    JTextArea getLogArea() {
        return logArea;
    }
    
    /**
     * get closeButton - support for testing
     * @return closeButton
     */
    JButton getCloseButton() {
        return closeButton;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();

        logArea.setColumns(20);
        logArea.setRows(5);
        jScrollPane1.setViewportView(logArea);

        closeButton.setText("Close");
        closeButton.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logArea;
    // End of variables declaration//GEN-END:variables
}
